### ISSUE TITLE
src ext get fails with error

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/src-cli#36] opened 2019-01-10 20:51 UTC
```
> src ext get felixfbecker/lang-typescript
GraphQL errors:
[
  {
    "locations": [
      {
        "column": 9,
        "line": 25
      }
    ],
    "message": "Cannot query field \"title\" on type \"ExtensionManifest\"."
  }
]
```

**Comment by mrnugget** [comment] 2020-02-13 10:37
I cannot reproduce this:

```sh
$ src ext get sourcegraph/git-extras
{
  "ID": "UmVnaXN0cnlFeHRlbnNpb246eyJsIjo3Nn0=",
  "UUID": "2cd34b59-094b-4866-a975-de1ba019193f",
  "ExtensionID": "sourcegraph/git-extras",
  "Name": "git-extras",
  "CreatedAt": "2018-10-29T01:39:47Z",
  "UpdatedAt": "2018-10-29T01:39:47Z",
  "URL": "/extensions/sourcegraph/git-extras",
  "RemoteURL": "",
  "RegistryName": "",
  "IsLocal": true,
  "Manifest": {
    "Raw": "{\n  \"activationEvents\": [\n    \"*\"\n  ],\n  \"browserslist\": [\n    \"last 1 Chrome versions\",\n    \"last 1 Firefox versions\",\n    \"last 1 Edge versions\",\n    \"last 1 Safari versions\"\n  ],\n  \"commitlint\": {\n    \"extends\": [\n      \"@commitlint/config-conventional\"\n    ]\n  },\n  \"contributes\": {\n    \"actions\": [\n      {\n        \"actionItem\": {\n          \"description\": \"${config.git.blame.lineDecorations \\u0026\\u0026 \\\"Hide\\\" || \\\"Show\\\"} Git blame line annotations\",\n          \"label\": \"Blame\",\n          \"pressed\": \"config.git.blame.lineDecorations\"\n        },\n        \"category\": \"Git\",\n        \"command\": \"updateConfiguration\",\n        \"commandArguments\": [\n          [\n            \"git.blame.lineDecorations\"\n          ],\n          \"${!config.git.blame.lineDecorations}\",\n          null,\n          \"json\"\n        ],\n        \"id\": \"git.blame.toggle\",\n        \"title\": \"${config.git.blame.lineDecorations \\u0026\\u0026 \\\"Hide\\\" || \\\"Show\\\"} blame\"\n      }\n    ],\n    \"configuration\": {\n      \"properties\": {\n        \"git.blame.decorateWholeFile\": {\n          \"default\": false,\n          \"description\": \"Whether to decorate all lines in a file, rather than just selected lines.\",\n          \"type\": \"boolean\"\n        },\n        \"git.blame.lineDecorations\": {\n          \"default\": false,\n          \"description\": \"Whether to show Git blame annotations at the end of each line.\",\n          \"type\": \"boolean\"\n        }\n      },\n      \"title\": \"Git extras\"\n    },\n    \"menus\": {\n      \"commandPalette\": [\n        {\n          \"action\": \"git.blame.toggle\",\n          \"when\": \"resource\"\n        }\n      ],\n      \"editor/title\": [\n        {\n          \"action\": \"git.blame.toggle\",\n          \"when\": \"resource \\u0026\\u0026 clientApplication.isSourcegraph\"\n        }\n      ]\n    }\n  },\n  \"dependencies\": {\n    \"date-fns\": \"^2.0.0-alpha.24\",\n    \"rxjs\": \"^6.4.0\",\n    \"tagged-template-noop\": \"^2.1.0\"\n  },\n  \"description\": \"A Sourcegraph extension that adds useful features when viewing files in a Git repository on Sourcegraph, GitHub, GitLab, and other supported code hosts.\",\n  \"devDependencies\": {\n    \"@commitlint/cli\": \"^8.3.5\",\n    \"@commitlint/config-conventional\": \"^8.3.4\",\n    \"@sourcegraph/prettierrc\": \"^2.2.0\",\n    \"@sourcegraph/tsconfig\": \"^4.0.0\",\n    \"@sourcegraph/tslint-config\": \"^13.4.0\",\n    \"@types/expect\": \"1.20.4\",\n    \"@types/lodash\": \"4.14.149\",\n    \"@types/mocha\": \"5.2.7\",\n    \"@types/node\": \"10.12.18\",\n    \"@types/sinon\": \"7.0.13\",\n    \"expect\": \"^24.1.0\",\n    \"husky\": \"^1.3.1\",\n    \"lnfs-cli\": \"^2.1.0\",\n    \"lodash\": \"^4.17.11\",\n    \"mkdirp\": \"^0.5.1\",\n    \"mocha\": \"^6.1.4\",\n    \"nyc\": \"^13.3.0\",\n    \"parcel-bundler\": \"^1.12.3\",\n    \"prettier\": \"^1.19.1\",\n    \"sinon\": \"^7.3.2\",\n    \"source-map-support\": \"^0.5.12\",\n    \"sourcegraph\": \"^23.0.1\",\n    \"ts-node\": \"^8.3.0\",\n    \"tslint\": \"^5.11.0\",\n    \"typescript\": \"^3.3.3333\",\n    \"vscode-languageserver-types\": \"^3.14.0\"\n  },\n  \"extensionID\": \"sourcegraph/git-extras\",\n  \"files\": [\n    \"dist\"\n  ],\n  \"husky\": {\n    \"hooks\": {\n      \"commit-msg\": \"commitlint -e $HUSKY_GIT_PARAMS\"\n    }\n  },\n  \"icon\": \"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAX8AAAF/CAMAAACWmjlVAAAAM1BMVEXwUDPwUDPwUDPwUDPwUDPwUDPwUDPwUDPwUDPwUDPwUDPwUDPwUDPwUDPwUDPwUDPwUDPNJiJ+AAAAEHRSTlMA8DAQ0KDAQGCA4CCQUHCw+BUOAQAACLtJREFUeAHs0YNhRQEAwMBv4+0/bW0zxWWE3Oi3tl8vNsN548VuPx19Y1rOx8PdjntXvqvVZnikzcqZ72iyGJ5otnTny1sPz7Tz52ubHodnm009+sr9s+GFZluXkv1XjSc+BfsBBPsBBPsBZPsBpPsBpPsBpPsBpPsBpPsBpPsBpPsBpPsBpPsBpPsBtPt7APt7APt7APt7APt7APt7APt7APt7APt7APt7APt7APt7APt7APt7APt7APt7APt7APt7APt7APt7AP8BAAAgAAAEAIAABAEAIAAABACAAAD4N38BpPtncwBNV28BpPsBpPsBpPsBpPsBpPsBpPsBpPsBpPsBpPsBpPsBpPsBpPsBpPsBpPsBpPsBpPsBpPsBpPsBpPsB1PsB9PsB9PsB9PsB9Ps/DnDC3n0gWYoDURR9QgaE+7n/1c6Eb28yWnGJRG8FXed28W2J1s7ee21lBvDx+wOkun1ps96fGcDB7wjws+WtAAHC8fsDSGsLEIDn9wfQWgIE4Pn9AdRngC/4gQDLHiAAz29W5+HdJL8/gGqgAH7+GQDlRwMUOADPzwbIOxqA56cDLAYG4Pn5ADcZgOfnAxQwAM/PB1gNDMDz8wEaGIDn5wOsBgSIyG92ybMGBAjJn7I824wLwPPzDwDZgAAB+e2Sbx8gQEB+y9xrMD4Az1/k3GJAgHD8dso7AwKE47cu7woQIBy/rfKuGReA5+f9TwMCROO3Rd51AwJE4zdx/nwAnt8y588H4PltBf39AXh+3v9jQIBo/LZxzz/5ADy/dXmXDAgQjd8+cu4wAwJE47ck5y7jAvD8/AuwakCAePx2y7fduAA8P/8BQDIuAM/PX4AWIEBEfquaAUB+s2MGIPmtagYA+c2WGYDkt6YZAOQ3u2cAkt9smQFIfkt5BgD5zcoMwPDPADz/DMDzm+1LgAA0/3wayvP7144IAXh+/84cIADP71+qOUAAnt+/VXED+Pl5/yVAAD8/79+2AAH8/Ly/RQjg5+f9IwTw8/P+EQL4+Xn/CAH8/Lx/hAB+ft4/QgA/P+8fIYCfn/ePEMDPz/tHCODn5/0jBPDz8/4RAvj5ef8IAfz8vH+EAH5+3j9CAD8/7x8hgJ+f948QwM/P+wcIkIsF8H9iAIAf8H9wAIAf8H9wAIAf8PcFKLVv6/+7+tmAAAP4AX9ngHau+mrruQMBcrGI/rbJsaUOCQDwo/7+ADrOEQEAftbfH0BHGxAA4If9/QG0pQEBAH7Y3x9gKQMCAPywvz9AbgMCAPyAvyMAcDtbgB/wf1gAgB/w9wcY7JOOEef08v6jAqSRf8vcLYz/qADrwBN1FovjPyzAOe5Y5RbIf1iAvI86UWezQP7jAmyjrkB7JP+BAfYx91VcLZK/IwD8C1Df55/k2phHgPQ+//qUp0BVuux9/stTbueZpP4+/yQ95wLU3uf/eczbcHZrf5//LT3lJUCVvc9/1XPeBHqjf37O/ZzTG/31HH97of8u8n5607+F8/dv+ifjNv3LgKSBr//F/vGaTuM2n/+cuozbfP6/KRu3+fr3kD6v8+9y7h5xY8vLqM33P+9Xfv6eHnM78/zG75+YXXJtGXRXxTI//2UuP4fjYT2Cf8qP+A7u6fhgP4S/3U/49GvPjtfVMfx3ObaP+yFyeZe/df7J/+04giKMf8r01b9KQADa3/8a7DOAHwjA+vu/g3sN4AcD8P5pAW+cVCU2AO9vJWN//1gdkcP5W8kcPx+A97eSOX4+AO9vJXP8fADe39JKPPQCAWh//wvhbsP4+QC8v5VVv9haRvLzAXh/s/bTAsfHBvPzAXh/s7bpB7uaAfxAANzfLNXt0BfLV00G8AMBUP8vt7fe73W9e2+7mQH8QADAH1qVuADTv0pcgOlfJS7A9K8SF2D6V4kLMP2rxAWY/lXiAkz/KnEBpn+VuADTv0pcgOlfJS7A9K8SF2D6V4kLMP2rxAWY/lXiAkz/KnEBpn+VuADTv0pcgOlfJS7A9K8SF2D6V4kLMP2rxAWY/lUKHWDv2eEP8IcMkLrk+MImwB8ywCfrV1t3nj9wgHTpN8snzR84QDkcd0wG+IMGaNn7L+T5+QDxv79dpcABmuNfCPBHDVAydlInz88HSAt3Wg/Pzwe4gKPKaX4+gP+8niMB/GEDpEN/uw7whw3QkfPyeH4+gP/Azg3gDxrglGcJ4I8Z4JBnHeAPGaDItQPgDxnglm8F4I8Y4JBvJ8AfMMAu51aAP2CAj7wD+AMG6PJuB/jjBbjkXQP44wVY5d0J8vMBeP8O8McLIMSf5+cD8P48Px9gAf15fj7A6vcH+fkAvH8D+OMF6PKugPx8AP7njcDPByhybgH4IwbI8u0G+CMG2OTbh+PnA/A/dA7CzwfI8mwD+fkA/AWoAPwxA+xybAX5+QD8L0AD+KMG2DP435/n5wN08rNfnp8PsIBvffL8fICSwasPz88HqOBfv1RpBujs/XpngO3p/DPA5OcfAw6AP1wA/wkcVxrHPwOky3H8D8AfNoC1Qz/fto/mnwGsHg59gD9sAGtb1rc7+m6T3xHAt09fv7C/zmI2+V0B/Ev/tUcXBw5AARBCiUzc+q927bTufyJQAm/x1OlfCgjQKyCA+8cDuF+AgADuHw/gfgECArh/PID7BQgI4P7xAO4XICCA+8cDuF+AgADuHw/gfgECArh/PID7BQjcKID7BQgIcKP7BQgIcKP7BQgIcKP7BQjFBAjFBAjFBAjFBAjFBAjFBAjFBAjFBAjFBAjFBAjFBAjFBAjFBAjFBAjFBAjFBAjFBAjFBAjFBAjFBAjFBAjFBAjfzLZz91ebza9ivwChmAChmAChmAChmAChmAChmAChmAChmAChmAChmAChmAChmAChmAChmAChmAChmAChmAChmAChmADhPxNgcfqwA/+brU/vt1ny39l0cXqn3YwB2fJNgWwZlE0zOT1rfpgxNAkOWTwizBe71ZYL7Q7H02m600+YOAAAAABJRU5ErkJggg==\",\n  \"license\": \"MIT\",\n  \"main\": \"dist/sourcegraph-git-extras.js\",\n  \"name\": \"git-extras\",\n  \"nyc\": {\n    \"exclude\": [\n      \"**/*.test.ts?(x)\",\n      \"src/util/stubs.ts\"\n    ],\n    \"extension\": [\n      \".tsx\",\n      \".ts\"\n    ],\n    \"include\": [\n      \"src/**/*.ts?(x)\"\n    ]\n  },\n  \"publisher\": \"sourcegraph\",\n  \"readme\": \"# sourcegraph-git-extras\\n\\n[![build](https://travis-ci.org/sourcegraph/sourcegraph-git-extras.svg?branch=master)](https://travis-ci.org/sourcegraph/sourcegraph-git-extras)\\n[![codecov](https://codecov.io/gh/sourcegraph/sourcegraph-git-extras/branch/master/graph/badge.svg?token=c3KpMf1MaY)](https://codecov.io/gh/sourcegraph/sourcegraph-git-extras)\\n[![code style: prettier](https://img.shields.io/badge/code_style-prettier-ff69b4.svg)](https://github.com/prettier/prettier)\\n\\nA [Sourcegraph extension](https://docs.sourcegraph.com/extensions) that adds useful features when viewing files in a Git repository on [Sourcegraph](https://sourcegraph.com), GitHub, GitLab, and other [supported code hosts](https://docs.sourcegraph.com/extensions):\\n\\n- **Git: Show/hide blame**: toggles Git blame annotations with each line's last commit, author, date, etc.\\n\\n[**🗃️ Source code**](https://github.com/sourcegraph/sourcegraph-git-extras)\\n\\n[**➕ Add to Sourcegraph**](https://sourcegraph.com/extensions/sourcegraph/git-extras)\\n\\n![screenshot from 2018-10-28 17-55-20](https://user-images.githubusercontent.com/1976/47624533-f3a1e800-dada-11e8-81d9-3d4bd67fc08a.png)\\n![screenshot from 2018-10-28 17-55-02](https://user-images.githubusercontent.com/1976/47624534-f3a1e800-dada-11e8-9c08-9ce307653b20.png)\\n\",\n  \"repository\": {\n    \"type\": \"git\",\n    \"url\": \"https://github.com/sourcegraph/sourcegraph-git-extras.git\"\n  },\n  \"scripts\": {\n    \"build\": \"parcel build --no-minify --out-file sourcegraph-git-extras.js src/extension.ts\",\n    \"cover\": \"TS_NODE_COMPILER_OPTIONS='{\\\"module\\\":\\\"commonjs\\\"}' nyc --require ts-node/register --require source-map-support/register --all mocha --opts mocha.opts --timeout 10000\",\n    \"prettier\": \"prettier '**/*.{js?(on),ts?(x),scss,yml,md}' --write --list-different\",\n    \"prettier-check\": \"npm run prettier -- --write=false\",\n    \"serve\": \"yarn symlink-package \\u0026\\u0026 parcel serve --no-hmr --out-file sourcegraph-git-extras.js src/extension.ts\",\n    \"sourcegraph:prepublish\": \"yarn typecheck \\u0026\\u0026 yarn test \\u0026\\u0026 yarn build\",\n    \"symlink-package\": \"mkdirp dist \\u0026\\u0026 lnfs ./package.json ./dist/package.json\",\n    \"test\": \"TS_NODE_COMPILER_OPTIONS='{\\\"module\\\":\\\"commonjs\\\"}' mocha --require ts-node/register --require source-map-support/register --opts mocha.opts\",\n    \"tslint\": \"tslint -c tslint.json -p tsconfig.json './src/*.ts?(x)' './*.ts?(x)'\",\n    \"typecheck\": \"tsc -p .\"\n  },\n  \"title\": \"Git extras\",\n  \"url\": \"https://sourcegraph.com/-/static/extension/3438-sourcegraph-git-extras.js?c0jcj151tssg--sourcegraph-git-extras\",\n  \"version\": \"0.0.0-DEVELOPMENT\"\n}",
    "Title": "",
    "Description": "A Sourcegraph extension that adds useful features when viewing files in a Git repository on Sourcegraph, GitHub, GitLab, and other supported code hosts.",
    "BundleURL": "https://sourcegraph.com/-/static/extension/3438-sourcegraph-git-extras.js?c0jcj151tssg--sourcegraph-git-extras"
  }
}
```

Is this still valid?

**Comment by felixfbecker** [comment] 2020-02-13 19:14
First I thought "probably not", but I still get the same error as in the original post (no matter which extension I query). Some more info:
- My `src-config.json` points to sourcegraph.com
- I updated to the latest version just now

**Comment by eseliger** [comment] 2022-11-16 14:46
Extensions have been deprected, so I am going to close this ticket as part of some backlog grooming. Please reopen if you think we should still care about it.

**Closed by eseliger** 2022-11-16 14:46 UTC
