### ISSUE TITLE
Creating campaign actions causes jittery progress updates when a lot of repos are involved

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/src-cli#223] opened 2020-06-09 18:51 UTC
The video doesn't really capture all the jitteryness, perhaps due to recoding framerate.: https://p-YvFVk4.t1.n0.cdn.getcloudapp.com/items/E0uz8X92/Screen%20Recording%202020-06-09%20at%2011.42%20AM.mp4

**Comment by nicksnyder** [comment] 2020-06-09 20:26
I would rather see output streamed (e.g. when a repo is done, emit a line)

**Comment by mrnugget** [comment] 2020-06-10 06:25
Duplicate of https://github.com/sourcegraph/src-cli/issues/118.

@nicksnyder regarding the "one line per repo": try `src -v action exec`, note the `-v`. I'm wondering whether we shouldn't make that the default.

**Closed** 2020-06-10 08:57 UTC
