### ISSUE TITLE
Allow steps to continue on error

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/src-cli#381] opened 2020-11-14 01:06 UTC
In some circumstances, an error encountered when running a step causes the campaign preview or apply operations  to fail. 

Allowing the operation to continue on error (perhaps as an argument) would allow users to take advantage of the local cache to quickly re-run only the errant repositories.

**Comment by mrnugget** [comment] 2020-11-16 08:05
Can you provide more details? I'm not sure whether this is a duplicate of https://github.com/sourcegraph/src-cli/issues/379 or not.

**Comment by rrhyne** [comment] 2020-11-16 20:17
@mrnugget This is in relation to the recent customer with the large campaign where a networking issue caused them to have to start over again. I think it is the same. If so, close whichever ticket is the least approproate.

**Comment by chrispine** [comment] 2020-11-16 23:24
I'm pretty sure it is a dupe, so I will close this one (because I prefer to have all issues in the sg/sg repo).

**Closed by chrispine** 2020-11-16 23:24 UTC
Labels: team/campaigns
