### ISSUE TITLE
src serve-git does not detect repos if CWD is a symlink

### ISSUE THREAD

**Issue by mattboehm** [sourcegraph/src-cli#453] opened 2021-02-02 22:36 UTC
I have `~/repos` symlinked to `~/Dropbox/repos`. If I `cd` into `~/repos` and run `src serve-git`, the server starts and appears to be hosting all of the files, but going to `/v1/list-repos` shows that no repos were detected. If I run the same command from the actual directory, it works and detects all of my repositories.

**Comment by chrispine** [comment] 2021-02-02 23:23
Thanks for the report, we will look into this.

**Comment by mrnugget** [comment] 2021-02-03 08:07
@keegancsmith assigning to you for now, since you built `serve-git` and might have a hunch as to what the problem is. Otherwise, we can plan this in the next campaigns sprint.

**Closed** 2021-02-04 05:46 UTC
